---
server: 
  port: ${PORT:9090} 
  
spring:
  application:
    name: eureka-server
  profiles: prod
eureka: 
  instance: 
    hostname: ${DOMAIN_NAME}
  client: 
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/