server: 
  port: ${PORT:9090} 
spring:
  application:
    name: eureka-server
eureka: 
  instance: 
    hostname: 52.6.70.185
  client: 
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/